 
BACKEND_MYSQL_PORT: "3306"
BACKEND_MYSQL_HOST: "mysql.data.svc.cluster.local"

BACKEND_ELASTICSEARCH_PORT_UI: "9200"
BACKEND_ELASTICSEARCH_PORT_COMM: "9300"
BACKEND_ELASTICSEARCH_HOST: "elasticsearch.data.svc.cluster.local"

SLS_DEBUG: "*"